# Generated by Django 2.0.4 on 2021-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210212_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=15000),
        ),
    ]
